// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrmavezdhdllzzobmmhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndybWF2ZXpkaGRsbHp6b2JtbWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzI4MDEsImV4cCI6MjA2NDk0ODgwMX0.ZzmqYw1U9yUV8KOvHBaABW6OW8aVNa8NoKnbq5JTPYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);